### ISSUE TITLE
Cannot add Temperature to a Fan

### ISSUE THREAD

**Issue by mattwakeman** [hardillb/node-red-contrib-googlehome-web#1]
When selecting a Device Type of a Fan, it's not possible to select the Trait of Temperature.

**Comment by hardillb** [comment]
Yeah, it's not currently in the list.

I'm keeping the devices simple while I get state reporting back to the Home Graph working.

Longer term I will expand the options and I'm thinking about adding an expert mode that will allow people wishing to live dangerously to add any trait type they want to devices.
