### ISSUE TITLE
Homegraph not syncing

### ISSUE THREAD

**Issue by mattwakeman** [hardillb/node-red-contrib-googlehome-web#10]
I removed all of my devices from the web app, created a new device and tired to 'sync devices' from Google Home - now everything is our of sync.

**Comment by hardillb** [comment]
Try syncing again. The action had got into the state where it wouldn't do any actions until I remove/add somebody to white list

**Comment by mattwakeman** [comment]
"sync devices" - Sure, syncing devices for TP-Link Kasa
Yeelight, and Nest. The account owner
will need to sync Node-RED. Sorry, an
error occurred while syncing Node-RED.

**Comment by hardillb** [comment]
Try again, and if that doesn't work follow the link in the email I've forwarded to make sure it's enabled for you again.

But It's not my end as it didn't even register as a incoming http request.

**Comment by mattwakeman** [comment]
Fixed it!
