### ISSUE TITLE
"Something went wrong" pop up in Google home app

### ISSUE THREAD

**Issue by ItsJustDylan** [hardillb/node-red-contrib-googlehome-web#100]
Any device I create appears in the google home app but when toggled the device shows on until the "Something went wrong" message appears at the bottom of the screen and then the device shows as off again. 
Devices created before today, including one created yesterday work correctly but anything since around 23:30 yesterday (28/8/24) does not work.

**Comment by hardillb** [comment]
That message normally means that there hasn't been a response sent back to Google.

How have you configured the input node? is the "Auto Acknowledge" box ticked? If not you must have a response node and send the response in under 3 seconds.

**Comment by ItsJustDylan** [comment]
Ah, of course! Apologies, it was absolutely this. PEBCAC! 
Would you like me to delete this 'issue' record as not actually an issue?!
Thank you very much for your prompt response as well!
