### ISSUE TITLE
skill is currently experiencing a problem at the moment

### ISSUE THREAD

**Issue by ramanvda** [hardillb/node-red-contrib-googlehome-web#101]
Hello, 

Service is down : 

"Node-RED Google Assistant Smart Home Skill Bridge
It looks like the skill is currently experiencing a problem at the moment. Give it a couple of minutes and if it's still a problem please check if there is an existing open issue on GitHub here, if not then raise one."

**Comment by hardillb** [comment]
Should be fixed now
