### ISSUE TITLE
Thermostat doesnt seem to work

### ISSUE THREAD

**Issue by mattwakeman** [hardillb/node-red-contrib-googlehome-web#2]
- Created Device in Web App
- Specified Device Type of Thermostat 
- Specified Temp as Trait 
- Dragged Google Home node to canvas
- Logged in via node conf
- Attached a single function node and a debug node, didn't edit the function node

Open Google Home app on Android - The Thermostat appears but doesn't have any Modes (My Nest shows Heat, Eco, Off) and I cannot set the temperature.

Using Voice to command - "Set Thermostat to 20 degrees" opens the device via Home, shows "In Your Home" but again doesn't set the temp or allow me to interact. 

Do I need to use the Google Home Response Node or something to being the thermostat to life?

**Comment by hardillb** [comment]
You shouldn't need a response node yet.

But it does look like the Home Graph needs to have a starting state before it will interact with the TemperatureControl Trait.

I need to add some code to set the defaults for this trait.

Modes will come later, along with toggles but I need to come up with a nice way to enable them.

Heating and Cooling are already baked into the thermostat and should show up once it has a starting some temperatures.

I have inject a 20degree ambient and 20degree set point and as a starting state so it should come to life now.

Having now got a better handle on how things work after having people poke at it for a week, I need to rejig the data model a little to make some of this easier to deal with.

I've added temp control to my test fan, but it's still now showing any controls in the phone UI, but it does respond to voice.

**Comment by hardillb** [comment]
As a side note, you should only ever have to enter the username/password into a config node once for the first GoogleHome node you setup.

After that you should use the drop down to select the username from the list rather than create a new one. If you have more than one with the same username/password they will get into a reconnection loop because they will use the same client id on the MQTT broker.
