### ISSUE TITLE
Device list in node is empty.

### ISSUE THREAD

**Issue by Sjoerd1953** [hardillb/node-red-contrib-googlehome-web#21]
The device list in the google home node is empty. When I try to log in is get this:

It looks like the skill is currently experiencing a problem at the moment. Give it a couple of minutes and if it's still a problem please check if there is an existing open issue on GitHub here, if not then raise one.

For over 15 minutes now. Is that more than a couple? 😉

**Comment by hardillb** [comment]
Back up

**Comment by Sjoerd1953** [comment]
Thank you. I just started with this node this morning, works great. Is this interruption a daily routine?

**Comment by hardillb** [comment]
Nope, it's not been down for a few months

**Comment by Sjoerd1953** [comment]
Ok, thank you.
