### ISSUE TITLE
Remove private keys from github

### ISSUE THREAD

**Issue by Steve2955** [hardillb/node-red-contrib-googlehome-web#22]
First Of All I am not an expert in web security. But as far as I am concerned private keys are meant to be kept private. Currently the private SSL key (```server.key```) of this project is clearly visible for everyone. Maybe check this out for [some further reading](https://github.blog/2013-01-25-secrets-in-the-code/). 

You should definitly remove the ```server.key``` and ```server.crt``` from the repository and consider them to be compromised.

**Comment by hardillb** [comment]
Those keys are only used for local testing while developing, they are not used for any real deployment.

If you check [this](https://github.com/hardillb/node-red-contrib-googlehome-web/blob/master/index.js#L238) line in index.js you will see it only uses those keys if it's being run bound to localhost.

**Comment by Steve2955** [comment]
Alright, thank you very much for clarifying that. This actually makes a lot of sense. 
Have a nice day.
