### ISSUE TITLE
action.devices.commands.ColorAbsolute doesnt always return spectrumRGB

### ISSUE THREAD

**Issue by mattwakeman** [hardillb/node-red-contrib-googlehome-web#3]
The colour options which appear on the Google Smart Display do not always return a spectrumRGB value.

All return a name and some return temperature. 

It would be great if we were able to specify the colour options and their return object parameters via the Bridge Web App.

**Comment by hardillb** [comment]
We have very little control over what Google sends (https://developers.google.com/actions/smarthome/traits/colorsetting).

You can set the min/max color temperature values the device supports (I've set it to 2000k to 6500k) and you can set if it sends color values as RGB ot HSV (i default to RGB as it's easier to understand).

No mater if it sends temperature or RGB it always sends a color name.

I'd need to see some examples of what you asked for and what you got.

**Comment by mattwakeman** [comment]
Selecting "Ivory" from the Smart Display touch screen colour picker

```
{
   "command":"action.devices.commands.ColorAbsolute",
   "params":{
      "color":{
         "name":"ivory",
         "temperature":6000
      },
      "online":true
   }
}
```

Selecting "navy blue" via the Smart Display touch screen colour picker 

```
{
   "command":"action.devices.commands.ColorAbsolute",
   "params":{
      "color":{
         "name":"navy blue",
         "spectrumRGB":128
      },
      "online":true
   }
}
```

I'm assuming you specified the colour pallet (via the Bridge Web App) which is presented to the user via the Smart Display? Different colours provide different responses.

Ideally, when creating the light, it would be good to be able to specify the colour options. Looks like google have some rules where about what can and cannot happen simultaneously

**Comment by hardillb** [comment]
OK, so the you'll get color temperature values for any shades of white and spectrumRGB values for anything else.

I could break the RGB and colour temperature traits out as separate selections (or it can be another option for expert mode)

**Comment by mattwakeman** [comment]
So looking forward to expert mode
