### ISSUE TITLE
Skill bridge not reachable

### ISSUE THREAD

**Issue by geoffreydemaagd** [hardillb/node-red-contrib-googlehome-web#30]
Hi,

The site https://googlehome.hardill.me.uk/ is not accessible right now.

Node-RED Google Assistant Smart Home Skill Bridge
It looks like the skill is currently experiencing a problem at the moment. Give it a couple of minutes and if it's still a problem please check if there is an existing open issue on GitHub here, if not then raise one.

It this a known issue?

Many thanks

Geoffrey

**Comment by hardillb** [comment]
Back up, no obvious reason why it was down in the logs will check.

**Comment by geoffreydemaagd** [comment]
Thanks for the quick reponse and solution. Great work!
