### ISSUE TITLE
It looks like the skill is currently experiencing a problem

### ISSUE THREAD

**Issue by N0NameN0** [hardillb/node-red-contrib-googlehome-web#32]
Node-RED Google Assistant Smart Home Skill Bridge
It looks like the skill is currently experiencing a problem at the moment. Give it a couple of minutes and if it's still a problem please check if there is an existing open issue on GitHub here, if not then raise one.

any news ?

**Comment by hardillb** [comment]
Back up. Something is blowing the memory up and I've not tracked it down yet.
