### ISSUE TITLE
Nodes are always switching from connected to disconnected

### ISSUE THREAD

**Issue by Alopiso** [hardillb/node-red-contrib-googlehome-web#35]
Hi everyone! I made a node-red flow and it was working really well until a few days ago.
I can see that the nodes from the google home devices are always switching from connected to disconnected and then to connected again and so on...
What happens?

Thank yoU!

**Comment by hardillb** [comment]
You need to make sure you only have one config node shared between all the device nodes.

That our you have the same user on multiple Node-RED instances, this is not allowed.

**Comment by Alopiso** [comment]
> You need to make sure you only have one config node shared between all the device nodes.
> 
> That our you have the same user on multiple Node-RED instances, this is not allowed.

Yes, the problem was that I was using the same user in two Node-Red instances. Thank you so much!
