### ISSUE TITLE
Bridge down?

### ISSUE THREAD

**Issue by geoffreydemaagd** [hardillb/node-red-contrib-googlehome-web#36]
Hi,

I think the bridge is down? When I try to sign in I get:

Node-RED Google Assistant Smart Home Skill Bridge
It looks like the skill is currently experiencing a problem at the moment. Give it a couple of minutes and if it's still a problem please check if there is an existing open issue on GitHub here, if not then raise one.

Many thanks

**Comment by hardillb** [comment]
Try again

**Comment by geoffreydemaagd** [comment]
You're the best!
