### ISSUE TITLE
Service seems down

### ISSUE THREAD

**Issue by syrm** [hardillb/node-red-contrib-googlehome-web#37]
Google Home on my phone works.
Google Home from my Speaker say NR-GAB is unavailable.

**Comment by hardillb** [comment]
I only have access to a phone at the moment and it's working fine from that, both voice and via the Home app.

This means that all the parts of the service that I have any control over is all working fine, so it has to be a problem on Google's side.

**Comment by syrm** [comment]
Yes same thing, here.
Thank you.

I let it open right now, to be sure its not a range of IP blocked or something like that.

**Comment by syrm** [comment]
Its working now.
