### ISSUE TITLE
Multiple users

### ISSUE THREAD

**Issue by Miendar** [hardillb/node-red-contrib-googlehome-web#38]
Hello, 

Exepted the following problem, the node works fine, thanks for the dev !
On my house we are 2 personnes using the google Home.
It seams that only one personne can be connected:
 - I'm logged then my wife is logged on google home -> only me can use the service. When my wife try a vocal command, the google home says that her nr-gab is not connected.
 - I remove service on both phone, I first install on her phone then on my phone, the problem is still present: only my wife can use the service...
 What is the trick to allow several personnes (living in the same house) using the service in the same time ?
 Thanks for support.

**Comment by hardillb** [comment]
You sign in with on use then share the "Home" with the other user.

https://support.google.com/googlenest/answer/9155535?hl=en-GB

**Comment by Miendar** [comment]
Thanks for feed back, it works fine.
I just assigned devices to a room...
