### ISSUE TITLE
Fan control in other languages

### ISSUE THREAD

**Issue by icarome** [hardillb/node-red-contrib-googlehome-web#40]
I'd like to be able to control my fan in my own language, i didn't find the right place to provide translations. I'd be glad to help with those if i'm put in the right direction

**Comment by hardillb** [comment]
``` speeds: [
                    {
                      speed_name: "Low",
                      speed_values: [
                        {
                          speed_synonym: [
                            "low", "slow"
                          ],
                          lang: "en"
                        }
                      ]
                    },
                    {
                      speed_name: "Med",
                      speed_values: [
                        {
                          speed_synonym: [
                            "medium", "mid"
                          ],
                          lang: "en"
                        }
                      ]
                    },
                    {
                      speed_name: "High",
                      speed_values: [
                        {
                          speed_synonym: [
                            "high", "full","max"
                          ],
                          lang: "en"
                        }
                      ]
                    }
                  ],
```

The `speed_name` can not be changed, but if you want to translate the `speed_synonym` values I'll try and have a look.

**Comment by icarome** [comment]
{
                      speed_name: "Low",
                      speed_values: [
                        {
                          speed_synonym: [
                            "mínimo", "um", "baixa", "mínima"
                          ],
                          lang: "pt-BR"
                        }
                      ]
                    },
                    {
                      speed_name: "Med",
                      speed_values: [
                        {
                          speed_synonym: [
                            "médio", "dois", "média"
                          ],
                          lang: "pt-BR"
                        }
                      ]
                    },
                    {
                      speed_name: "High",
                      speed_values: [
                        {
                          speed_synonym: [
                            "máximo", "três","máxima"
                          ],
                          lang: "pt-BR"
                        }
                      ]
                    }
                  ],


There it goes. Thanks for the quick reply!

**Comment by hardillb** [comment]
Hi, this has been deployed but you will need to delete and recreate the device for it to take effect.
