### ISSUE TITLE
Vacuum type

### ISSUE THREAD

**Issue by invender** [hardillb/node-red-contrib-googlehome-web#42]
Can i use a [vacuum](https://developers.google.com/assistant/smarthome/guides/vacuum) type and traits for it?

**Comment by hardillb** [comment]
No, not a the moment.

I have looked at it in the past, but too many of the traits require a lot of per user customisation (e.g. naming rooms/zones, defining runcycle types) and there isn't an easy way to present this to the user in the current device management scheme
