### ISSUE TITLE
Google Home Issues

### ISSUE THREAD

**Issue by robwilkes** [hardillb/node-red-contrib-googlehome-web#46]
Hi, I've added a device, linked account, the device shows in Google Home, when I query temperature or humidity, I get (incorrect) readings of 22 degrees and 50% humidity, however there is no output to the debug node, it doesn't appear as though the message hit my Node-Red at all.

![image](https://user-images.githubusercontent.com/4636768/117097629-7fcdae00-adaf-11eb-8bcf-79b7f6d76000.png)

This same device, and Node-RED, is working fine with your Alexa service, so I know it functionally all works, the problem seems specific to your Google Home plugin, and since there is no output to debug node I don't know where to start, I assume the problem is in the cloud.

![image](https://user-images.githubusercontent.com/4636768/117098024-ac35fa00-adb0-11eb-98e5-1ef2924fb1fb.png)

**Comment by robwilkes** [comment]
Just checked with tcpdump, there was no traffic to/from my Node-RED during the Google Home interaction, and Google Home returned fictitious temperature of 22 degrees.

**Comment by hardillb** [comment]
This is working totally as expected. Sensors do not issue commands, so there will never be anything from a GoogleHome-In node.

How to update the value is covered in the Sensors section at the end of the documentation https://googlehome.hardill.me.uk/docs

**Comment by robwilkes** [comment]
So this is a pretend service that does nothing at all, ok got it.
I've deleted your 'Google home' node from my Node-RED and Google Assistant still gives bogus responses of 22 degrees and 50% humidity, it's not talking to my Node-RED or sensor at all.

If this is working at intended I'll be moving to OpenHAB thanks.

**Comment by hardillb** [comment]
Have you read the docs or the blog post about Google Assistant sensors?

**Comment by robwilkes** [comment]
Your blog post makes more sense than the documentation, I'll give that a
shot.
