### ISSUE TITLE
scene problem

### ISSUE THREAD

**Issue by dcremo90** [hardillb/node-red-contrib-googlehome-web#49]
hello, I wanted to report a problem encountered on the scene this morning.  every time I call them, Google home he replies that he cannot find them.
THX

**Comment by hardillb** [comment]
I'm going to need a lot more information before I could start to look at this.

e.g.
- username
- name of scenes
- How long it's worked for (when you set up the scenes)
- did you change anything
- What EXACTLY did you ask Google to do
- What EXACTLY was the error message

Nothing has changed from the services point of view, so this may be a bug/change on Google's side and there would be little we would see or be able to do about it.

**Comment by dcremo90** [comment]
Oops sorry, my account is dcremo and I have problems with all the scenes created.  to recall a scene I use the Google home runtimes.  the problem started this morning but until last night everything worked.

Scarica Outlook per Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by hardillb** [comment]
OK, there is nothing obvious in the logs

And I can see a bunch of Scenes devices in the database.

My test Scene appears to still be working. Can I ask you to create a new Scene and add it to Node-RED with a debug node and check if that works.

**Comment by hardillb** [comment]
Closing as no update
