### ISSUE TITLE
service down

### ISSUE THREAD

**Issue by N0NameN0** [hardillb/node-red-contrib-googlehome-web#52]
Node-RED Google Assistant Smart Home Skill Bridge
It looks like the skill is currently experiencing a problem at the moment. Give it a couple of minutes and if it's still a problem please check if there is an existing open issue on GitHub here, if not then raise one.

**Comment by hardillb** [comment]
The site is up but the load is very high implying that a lot of people have multiple config nodes forcing mass reconnects.

**Comment by N0NameN0** [comment]
i confirm, it's slow but it's work. Do you plan a "premium" access or the ability to host ourself the bridge ? in my case it's very critical since a disabled family person depend a lot of it with nodered flows i created for her.

**Comment by hardillb** [comment]
I'm going to close this as the system is up, but may be running slowly until we can get the people spamming status updates to stop.

**Comment by hardillb** [comment]
No there is no premium service and you are free to take the code and try and run it yourself but I offer no support or instructions on how to do that and will not.

**Comment by N0NameN0** [comment]
> No there is no premium service and you are free to take the code and try and run it yourself but I offer no support or instructions on how to do that and will not.

thanks for your answer ( i accidently deleted my question ;) ) Can you just confirm that the actual git version is the current one you use ? i meant git is up to date ? ;)
