### ISSUE TITLE
Service down ? 

### ISSUE THREAD

**Issue by N0NameN0** [hardillb/node-red-contrib-googlehome-web#53]
Service seems to be down...
Do you need a "real" hosting service ?? i say that coz i'm working for a great hosting corp in France ;)

**Comment by pgScorpio** [comment]
Indeed offline again! 
Happens a lot lately, and it's a pain in the ass since I run a lot of scripts using this service.

**Comment by N0NameN0** [comment]
> Is it possible to run the service at home locally?

i already asked this !! i'm also for a "self hosting" politics, but @hardillb seems dont think this way. Or at least do not want to be annoyed about self hosting support.... ;) ;)

**Comment by hardillb** [comment]
You are welcome to take the code but I offer no instructions or support.

The problem appears to be load dependent, I will send the nastygrams to those that can't configure properly or are sending stupid numbers of status updates. I'll try and find some time at the weekend to try and move it to a slightly large AWS instance

**Comment by hardillb** [comment]
I've given it a kick and restarted the service, should be running now. As I said I'll try and move to a bigger instance at the weekend, so expect a little down time.

**Comment by hardillb** [comment]
Now running on a box with twice as many CPUs as before for a strangely cheaper cost, but then who can explain the mysteries of AWS EC2 billing...

**Comment by N0NameN0** [comment]
> Now running on a box with twice as many CPUs as before for a strangely cheaper cost, but then who can explain the mysteries of AWS EC2 billing...

cool and thanks !!! i hope something more stable now ;)
