### ISSUE TITLE
Device List empty in node-red

### ISSUE THREAD

**Issue by hivefly** [hardillb/node-red-contrib-googlehome-web#55]
Hi, I have devices set up and working but i am not able to set up new flows because the device list is not populated. is this an issue with the server or something on my side?  i can see devices on the website fine... thanks

**Comment by hardillb** [comment]
Have you hit the refresh button next to the list?

Also is there anything in the Node-RED logs when you hit that button (not the debug sidebar the actual node-red console log)

**Comment by hardillb** [comment]
Also some basic information about your setup would be helpful

 - NodeJS version
 - Node-RED version
 - Node Version
 - Environment (OS, docker, HA)?

**Comment by hivefly** [comment]
Thanks, I have tried refreshing with the button

I don't see anything coming up in the log when pressing the refresh button either

I'm running on a Pi, node red version 0.20.7
node version 0.0.10
i dont know how to find node js version sorry

updated to node version 0.0.14 and the problem persists

**Comment by hardillb** [comment]
Have you changed your password between setting up the old devices and the new ones?

You can find the NodeJS version by running `node --version`

Latest version of the node is 0.0.15 (I had forgotten to update flows.nodered.org).

Node-RED will log if there is an error when you push the refresh button but it might not be immediate.

What is the username you have for the service so I can check the logs for when it looks up the device list?

**Comment by hivefly** [comment]
nodejs v8.16.1
username: niblett

i have updated to 0.0.15 now thanks. still nothing in the log and the same issue.

thanks for looking into this for me

**Comment by hardillb** [comment]
The logs so no sign of you even trying to connect to the service to pull the device list down which means something very strange is going on.

Just to prove it is possible to retrieve the list from your machine,  please try and run the following command:
```
curl "https://niblett:password@googlehome.hardill.me.uk/user/api/devices"
```
replace `password` with your password

Also please supply the output of `lsb_release -a`

**Comment by hardillb** [comment]
Actually I think I might know what the problem is.

NodeJS version v8.16.1 is too old. (The current LTS version is 16.x)

NodeJS has a built in SSL certificate CA list, and the CA certificate for the Certificate Authority I use for the service changed recently so the version in the baked in CA list will have expired so it can no longer connect to the server.

You **REALLY** need to upgrade NodeJS (and you should really update Node-RED as well).

As a work around you can try exporting the `NODE_TLS_REJECT_UNAUTHORIZED=0` environment variable (beware, this totally disables all certificate checking.

**Comment by hivefly** [comment]
Thank you. I will do an update on both in the next day or so and report back.

**Comment by hivefly** [comment]
Hi, sorry it has been a while but i finally got on to updating everything and the problem persists unfortunately:

current:
nodejs v10.24.0
nodered v1.3.4

lsb_release -a gives the following:
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

curl "https://niblett:password@googlehome.hardill.me.uk/user/api/devices" pulls the device list etc so thats clearly working

still nothing in the log

something i may have overlooked before is that the refresh button is not actually clickable next to the device list. the mouse cursor does not change to a hand...

**Comment by hardillb** [comment]
Why/how did you only upgrade to Nodejs v10.24.0 and Node-RED v1.3.4? 

As I said latest LTS NodeJS is v16.x and Node-RED is at v2.2.2. The Node-RED install script would have installed script would have installed both of these. You REALLY need to go to a supported version of NodeJS, v10.x is also out of support as can be seen here:

https://nodejs.org/en/about/releases/

At the very least you should be aiming for NodeJS v14.x

The mouse cursor doesn't have to change, the button is clickable
