### ISSUE TITLE
Missing parameter value from Google

### ISSUE THREAD

**Issue by phguk** [hardillb/node-red-contrib-googlehome-web#70]
First time user with Google Assistant Bridge & Code Red so please bear with me.

I want to integrate a Sonoff S26R2 socket which I've flashed with Tasmota to Google Home. I've added the socket so it's visible to Google Home. However when I turn it on/off (from Google Home), the message generated has no parameter value - I was expecting to see OFF or ON (see below) per your documentation.

09/12/2022, 18:49:08[node: debug 2] (http://10.0.0.3:6335/#)
msg.payload : Object
{ command: "action.devices.commands.OnOff", params: object }

It occurs to me that perhaps Google Home doesn't know the socket status.  Should it, and if so - do I need to provide it to Google ?Given this is very basic, I must be doing something wrong. Any assistance appreciated.

Thanks Paul

**Comment by hardillb** [comment]
Expand the `params: object` entry

It contains `on: true` or `on: false` to represent the state the device is being commanded to.

**Comment by phguk** [comment]
Thanks & apologies for my basic mistake ;-)

**Comment by phguk** [comment]
Thanks & apologies for my basic mistake ;-)
