### ISSUE TITLE
Unable to connect to the service (EHOSTUNREACH)

### ISSUE THREAD

**Issue by Ayrton31** [hardillb/node-red-contrib-googlehome-web#71]
When I tried to access to the service, I encountered this error on Node Red

Error: connect EHOSTUNREACH 2a05:d018:8c4:3201:2a72:eccf:e8a:2b76:8883

**Comment by hardillb** [comment]
Sounds like you have a broken IPv6 setup

The machine running Node-RED appears to be  about to resolve hostnames to IPv6 addresses but unable to route to public IPv6 addresses.

You have 2 choices

1. fix your IPv6 rotuing
2. disable IPv6 on the machine running Node-RED
