### ISSUE TITLE
Nodes connect and disconnect radom

### ISSUE THREAD

**Issue by rvbaelen** [hardillb/node-red-contrib-googlehome-web#74]
It looks like the nodes in NR are disconnectiong and reconnecting every 5s. No clue what is the issue.

**Comment by hardillb** [comment]
You can only have 1 instance of Node-RED running with a given user
And you can only have 1 Configuration node (where you entered the username/password) that must be shared by all the device nodes.

Ensure you only have 1 instance of Node-RED running and delete duplicate config nodes

**Comment by hardillb** [comment]
From the docs:

> Configure Nodes
> 
> When you drag the first Google Home node on to the canvas you will need to create a config node. To do this, click on the pencil icon next to the first input. This will open a new dialog, where you can enter the same username/password from the first step and hit the "Add" button. **For all subsequent nodes you should just pick the entry from the drop down that matches your username.**
