### ISSUE TITLE
Light does not expose brightness

### ISSUE THREAD

**Issue by palsbo** [hardillb/node-red-contrib-googlehome-web#75]
Exelent program:) - however:
Light does not expose brightness to Google Home (latest preview version of Google Home for IOS)
All 3 boxes are ticked.

**Comment by hardillb** [comment]
Nothing has changed in the service, it's working five on Android.

Given that the preview version of the app is considered beta, I suggest you raise this with Google

**Comment by hardillb** [comment]
Nothing has changed in the service, it's working five on Android.

Given that the preview version of the app is considered beta, I suggest you raise this with Google 

Also try long pressing on the device buttons

**Comment by palsbo** [comment]
Which button???
Ok - it works with Google Home on Android.

**Comment by hardillb** [comment]
Sorry I was basing my answer on the Android app (I don't have any iOS devices).

A long press on the device buttons opens the full screen option for that device that has brightness controls, where as a short press only toggles on/off.

![Screenshot_20230221-144508](https://user-images.githubusercontent.com/1800845/220377046-77d74941-67b2-4785-93de-c48d4f82f98f.png)

I'm going to close this as this is a behaviour change in the GoogleHome app and not something the Action can control
