### ISSUE TITLE
Connecting problem.

### ISSUE THREAD

**Issue by TeknoManyi** [hardillb/node-red-contrib-googlehome-web#78]
Hi. I am sorry for my English. I have a problem with google home and alexa skill. "Error: getaddrinfo EAI_AGAIN googlehome.hardill.me.uk" Services is down? Or my node-red dont working? I was  using it for a few months.

![resim](https://github.com/hardillb/node-red-contrib-googlehome-web/assets/87738214/5759a26b-0213-4271-9ef9-2b0a4b2f1334)
![resim](https://github.com/hardillb/node-red-contrib-googlehome-web/assets/87738214/938f52d3-6aa8-4378-91c4-1b317ec8e5d3)

I will waiting for your answer. 

TeknoManyi

**Comment by hardillb** [comment]
That is a DNS problem on your end, nothing to do with the service.
