### ISSUE TITLE
nr-gab down

### ISSUE THREAD

**Issue by wink73** [hardillb/node-red-contrib-googlehome-web#81]
Hi, I've been having problems with nr-dag and google home for a couple of hours. Also when I try to access the site https://googlehome.hardill.me.uk/user/devices nothing happens. Thanks anyway because it's a fantastic service.

**Comment by hardillb** [comment]
Hi, something had pegged out the cpu on the host box, I've restarted and things look better, will keep an eye on it.

**Comment by wink73** [comment]
Now it works perfectly, thank you very much.
