### ISSUE TITLE
HELP - I have half a dozen virtual devices - were working no problem - hallway for example....

### ISSUE THREAD

**Issue by scargill** [hardillb/node-red-contrib-googlehome-web#82]
All just stopped yesterday or today and apparently my account has no virtual devices according to node-red - any ideas? Raspberry Pi 4 Node-Red - just upgraaded the lot to Node-RED 3 and nodejs18 in the last few days - I'm gutted... updated all nodes to latest. I can control the lot the old fashioned way so my eral devices are fine...

![image](https://github.com/hardillb/node-red-contrib-googlehome-web/assets/1889411/8c258ec4-74e5-4e7e-a5f9-5f94e07df050)

**Comment by hardillb** [comment]
EAI_AGAIN means your DNS is screwed, it can't resolve googlehome.hardill.me.uk.

Fix that first

**Comment by scargill** [comment]
Hi

Well, strange you mention that - I'd seen some issues on my RPI ersolving addresses when doing ap update... SO (years ago I set up a fixed IP on the Pi - so long ago I don;t remember what I did). 
  sudo nano /etc/dhcpcd.conf
No dhcpcd.conf - no idea why - so I simpl created one and added at the end... 
  static domain_name_servers=8.8.4.4 8.8.8.8

and if I (at ssh terminal) do this - ping googlehome.hardill.me.uk
 I get:
pi@mainpi:~:17:18[0]> ping googlehome.hardill.me.uk
PING googlehome.hardill.me.uk (34.241.226.122) 56(84) bytes of data.
64 bytes from ec2-34-241-226-122.eu-west-1.compute.amazonaws.com (34.241.226.122): icmp_seq=1 ttl=46 time=83.6 ms
64 bytes from ec2-34-241-226-122.eu-west-1.compute.amazonaws.com (34.241.226.122): icmp_seq=2 ttl=46 time=81.6 ms
64 bytes from ec2-34-241-226-122.eu-west-1.compute.amazonaws.com (34.241.226.122): icmp_seq=3 ttl=46 time=80.5 ms
64 bytes from ec2-34-241-226-122.eu-west-1.compute.amazonaws.com (34.241.226.122): icmp_seq=4 ttl=46 time=77.4 ms
64 bytes from ec2-34-241-226-122.eu-west-1.compute.amazonaws.com (34.241.226.122): icmp_seq=5 ttl=46 time=77.1 ms
64 bytes from ec2-34-241-226-122.eu-west-1.compute.amazonaws.com (34.241.226.122): icmp_seq=6 ttl=46 time=76.0 ms
64 bytes from ec2-34-241-226-122.eu-west-1.compute.amazonaws.com (34.241.226.122): icmp_seq=7 ttl=46 time=83.8 ms

Is that as it should be?

Erm, no...

```
pi@mainpi:~:17:24[0]> sudo apt update
Err:1 http://download.zerotier.com/debian/buster buster InRelease
  Temporary failure resolving 'download.zerotier.com'
Err:2 http://mirrordirector.raspbian.org/raspbian buster InRelease
  Temporary failure resolving 'mirrordirector.raspbian.org'
Err:3 http://archive.raspberrypi.org/debian buster InRelease
  Temporary failure resolving 'archive.raspberrypi.org'
Err:4 https://packages.grafana.com/oss/deb stable InRelease
  Temporary failure resolving 'packages.grafana.com'
Err:5 http://raspbian.raspberrypi.org/raspbian buster InRelease
  Temporary failure resolving 'raspbian.raspberrypi.org'
Err:6 https://deb.nodesource.com/node_18.x buster InRelease
  Temporary failure resolving 'deb.nodesource.com'
Err:7 https://repos.influxdata.com/debian buster InRelease
  Temporary failure resolving 'repos.influxdata.com'
Err:8 https://pkgs.tailscale.com/stable/raspbian buster InRelease
  Temporary failure resolving 'pkgs.tailscale.com'
Err:9 http://repository.picockpit.com/raspbian buster InRelease
  Temporary failure resolving 'repository.picockpit.com'
Err:10 https://download.docker.com/linux/raspbian buster InRelease
  Temporary failure resolving 'download.docker.com'
Err:11 http://ppa.launchpad.net/webupd8team/java/ubuntu xenial InRelease
  Temporary failure resolving 'ppa.launchpad.net'
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
W: Failed to fetch http://raspbian.raspberrypi.org/raspbian/dists/buster/InRelease  Temporary failure resolving 'raspbian.raspberrypi.org'
W: Failed to fetch http://mirrordirector.raspbian.org/raspbian/dists/buster/InRelease  Temporary failure resolving 'mirrordirector.raspbian.org'
W: Failed to fetch https://download.docker.com/linux/raspbian/dists/buster/InRelease  Temporary failure resolving 'download.docker.com'
W: Failed to fetch https://packages.grafana.com/oss/deb/dists/stable/InRelease  Temporary failure resolving 'packages.grafana.com'
W: Failed to fetch https://repos.influxdata.com/debian/dists/buster/InRelease  Temporary failure resolving 'repos.influxdata.com'
W: Failed to fetch https://deb.nodesource.com/node_18.x/dists/buster/InRelease  Temporary failure resolving 'deb.nodesource.com'
W: Failed to fetch http://repository.picockpit.com/raspbian/dists/buster/InRelease  Temporary failure resolving 'repository.picockpit.com'
```

No idea why its doing that but it looks like your comment correctly blames my Pi (it worked until a couple of days ago)...

**Comment by scargill** [comment]
Ah but then "hey google mancave on" just worked so maybe I did do some good.   minutes later I tried the apt update again and everrything except grafana worked - but there's a known issue with that now...
