### ISSUE TITLE
New Devices Unresponsive

### ISSUE THREAD

**Issue by baxtmi** [hardillb/node-red-contrib-googlehome-web#83]
Evening

I've been using the service for a year or 2 and it's working great. I've recently added a few new devices to my profile, and they are not performing as expected.

I add a new switch to my profile, I see the new switch in my google home account, I assign the switch to a home and a room, same as I've done with all the other devices. I then go into NR, drop in new send / receive google assistant blocks, link them to my account, select the new device from the dropdown, same as I've done for my other switches. 

Except for some reason, messages are not coming through from google when I toggle the switch there or get through when I toggle the switch from NR.

Ideas please?

**Comment by hardillb** [comment]
Has this resolved it's self?

What do you mean by "or get through when I toggle the switch from NR."? Sending a status update using the response node should not cause any messages to be sent, it just updates the logical status in the Google Home Graph (the Google Home App does **NOT** update in real time)

**Comment by baxtmi** [comment]
Good afternoon. Apologies, was also away.

To answer the first question, no this doesn't seem to have resolved itself.

Maybe to clarify from my side. Attached a few screen grabs as well.

The pool light is an existing switch I loaded quite some time back. When I toggle the switch in Google Home, I get basically real time feedback on the command, as you can see on the time stamps.

With any new switches that I add, they no longer respond at all to me toggling them in google home., regardless of how long I give it They are visible, there just seems to be a breakdown somewhere that stops the toggle message getting through.

![Untitled](https://github.com/hardillb/node-red-contrib-googlehome-web/assets/3080536/34fd707d-f7ec-476f-9ef3-c8593ceace07)

**Comment by hardillb** [comment]
I've just added a new switch to my account and then added the new node to Node-RED and it's working just fine, so I can't reproduce this.

Do you get events if you toggle the new device via voice?

Also there was a report from another user of things not working if the device name contained "pool" but that was only via voice and that is all on Google's side of things and I have no control over that.

If you can tell me your account name and the device name I can monitor the system to see if I can see requests to toggle it coming through

**Comment by baxtmi** [comment]
And true to form, this seems to be behaving flawlessly now.... mutter mutter mutter.... haha

Appreciate the help.

To comment on your pool thing, I have exactly the same issue. Tell google to turn on the pool light, and it's never heard of it. But tell google to turn the pool on, and it switches the light on.... But then to switch off, it works by telling google to turn the pool light off.... so who knows what they're playing at...
