### ISSUE TITLE
Light Brightness not Doing anything

### ISSUE THREAD

**Issue by hannaj19** [hardillb/node-red-contrib-googlehome-web#85]
![image](https://github.com/hardillb/node-red-contrib-googlehome-web/assets/144183063/49c1df37-b1ab-4ffb-8fc9-790b80f181fc)
The light object has both On/Off and Brightness selected, but when I open up the google home app it's as if there's no brightness control. Only on/off states are available.

Also a brightness slider does appear if I enable color controls, but it doesn't do anything in the node-red.

**Comment by hardillb** [comment]
This is going to be down to what Google choose to support in their mobile app, not the service.

Does brightness control work if commanded via voice?

**Comment by hannaj19** [comment]
I tried again today, and voice commands work.
Then I the app again and it worked, so I guess no problem lol!

Thanks!
