### ISSUE TITLE
Google home pool or pool light devices fail periodically

### ISSUE THREAD

**Issue by kevincw01** [hardillb/node-red-contrib-googlehome-web#86]
Seems very strange but I can reliably recreate an error only when the device has one of these names.  The error comes from google home/nest device when I ask it to turn on or off "sorry something went wrong and I'm unable to control your home device".  Sometimes I will get lucky and it will work but more often than not it gives me this error.  If I change the name without the word 'pool' it works fine every time.

**Comment by hardillb** [comment]
The service passes the name field directly to the service when the device is created or edited, then all the name matching is done on the Google Assistant side of things and the service gets passed an numerical id when the device is activated.

So unfortunately there is nothing I can do from my side to influence things.

My only suggestion is to make sure the lights are in a room called something like "Pool House" and then they should respond to things like "Turn on the Pool House lights" no matter what the device is called (assuming they have the light trait)

**Comment by kevincw01** [comment]
Very strange.  When I try that e.g. name 'light' and location 'pool' it also fails.  As soo as the word pool is deleted or changed it works

**Comment by kevincw01** [comment]
One work around which is silly is that I can say "turn off the light in the pool" then it works.  But flip it and say "turn off the pool light" and I get that error.

**Comment by hardillb** [comment]
All I can suggest is you raise this with Google (if you can find a way to raise a bug)
