### ISSUE TITLE
Cannot link NR-GAB account to Google Home

### ISSUE THREAD

**Issue by whyvra** [hardillb/node-red-contrib-googlehome-web#89]
Trying to set this up for a friend who just got some LEDs controlled by WLED. 

We've created an account and setup the flow in Node Red. When we try to link his account with NR-GAB to Google Home, we get a message saying that no compatible devices were found. I've tried setting up another device and still no luck.  The node in Node Red shows as connected. 

Username is Cojo2077.

Thanks

**Comment by hardillb** [comment]
I'm sorry, but all that is going to be on Google's side and not something I can influence.

**Comment by whyvra** [comment]
It is just time-delay or caching issue on Google's side? Maybe I'll need to try again in a hour or two..

**Comment by hardillb** [comment]
Try simpler devices, lights with just on/off, no brightness or colour settings.
