### ISSUE TITLE
Googlehome has just stopped working from yesterday

### ISSUE THREAD

**Issue by scargill** [hardillb/node-red-contrib-googlehome-web#91]
I'm getting a load of:
"Error: getaddrinfo EAI_AGAIN googlehome.hardill.me.uk"
messages all of a sudden, started yesterday I think. So I'm back to using my phone to turn things on and off.... no idea why this has started to happen... I cannot control lights now on my node-red setup via node-red-contrib-googlehome  

Any idea why?

**Comment by hardillb** [comment]
Your DNS is broken

**Comment by hardillb** [comment]
Also you have asked this before - https://github.com/hardillb/node-red-contrib-googlehome-web/issues/82

Please search old issue (especially your own)
