### ISSUE TITLE
Is the service down?

### ISSUE THREAD

**Issue by gpuccio87** [hardillb/node-red-contrib-googlehome-web#93]
It seems that the service is down. Cannot log in or unsubscribe from Google Assistant.

**Comment by whoo** [comment]
Hi,
Same here , timeout on:

https://googlehome.hardill.me.uk/auth/start?response_type=code&client_id=1&redirect_uri=https://oauth-redirect.googleusercontent.com/r/node-red-d955e&scope=access_devices&state=A....

**Comment by rclabpanama** [comment]
Hello everyone. We are also having the same problem here...
Thanks Mr. Hardill for the services offered by your servers. I wish you can fix the trouble soon.
Thank.

**Comment by hardillb** [comment]
Should be fixed now

**Comment by rclabpanama** [comment]
Thanks Mr. Hardill. The system is working nice again
Very very thanks
________________________________

**Comment by rclabpanama** [comment]
All is working now.
Thanks.
