### ISSUE TITLE
Service down?

### ISSUE THREAD

**Issue by kpodjuk** [hardillb/node-red-contrib-googlehome-web#95]
Hi, I have noticed that service is not responding anymore since this morning. 

Thanks in advance for taking care of the issue.

![2023-12-23 13_39_00-Node-RED Google Assistant Smart Home Skill Bridge](https://github.com/hardillb/node-red-contrib-googlehome-web/assets/62662345/2fb77101-20c9-46f1-971a-e5f13f981577)

**Comment by hardillb** [comment]
Should be back now, offender banned until they fix their status reporting.
