### ISSUE TITLE
Nodes keeps reconnecting

### ISSUE THREAD

**Issue by franckarts** [hardillb/node-red-contrib-googlehome-web#96]
Firstly, I want to express my gratitude for providing such a valuable tool; it has been incredibly helpful.

However, I've encountered an issue lately. My nodes in Node-RED are continuously attempting to reconnect, disrupting the workflow:
![Sélection_014](https://github.com/hardillb/node-red-contrib-googlehome-web/assets/5030247/25d5b594-df74-4c85-a19d-8a8b85a8c4d7)

I've double-checked the login credentials and even tried removing and recreating the node, but the problem persists.

Could it be that the service is currently experiencing downtime?

**Comment by hardillb** [comment]
Ensure you only have 1 `google-home-conf` node in Configuration Nodes list.

Also you can only have 1 Node-RED instance using the username.

**Comment by franckarts** [comment]
I only have one Google Home configuration and one Node-RED instance running. It was functioning perfectly before, and I haven't made any changes to my configuration.

**Comment by franckarts** [comment]
@hardillb Is it possible to re-open this ticket please ?

**Comment by hardillb** [comment]
The service is up and running just fine, so this is 100% on your end.

The other option is that your DNS is messed up. Check you can ping googlehome.hardill.me.uk from the machine running Node-RED.

**Comment by franckarts** [comment]
This is weird, I can ping without any issue.

**Comment by hardillb** [comment]
What do the Node-RED logs show?

Have you restarted Node-RED?

**Comment by franckarts** [comment]
Where are the logs please ? I don't see anything in /var/log or /config/node-red (I use home assistant).
Also, yes I have restarted the whole VM.

**Comment by hardillb** [comment]
You are on your own with Home Assistant, I don't use it.

**Comment by hardillb** [comment]
What is your username?

**Comment by hardillb** [comment]
Also if you are using Home Assistant you need to ensure you can resolve/ping the host name from INSIDE the container

**Comment by franckarts** [comment]
My username is franckarts. Yes I have tried in the container as well.

**Comment by franckarts** [comment]
![Sélection_016](https://github.com/hardillb/node-red-contrib-googlehome-web/assets/5030247/b302916d-fa28-40d3-b691-176280ae2301)

**Comment by hardillb** [comment]
No not the Home Assistant VM/Container, the Node-RED container that Home Assistant is running.

Anyway I can see you managed to connect about a little over 2 hours ago and not since, most likely this is a network issue on your end where the container can not connect to the service.

You will need to talk to the Home Assistant folks to work out why.

**Comment by franckarts** [comment]
I've successfully retrieved the logs, but unfortunately, there's nothing of interest in them. I've inserted my own log into `googlehome.js`, the reconnect event keeps triggering repeatedly. I've even attempted replacing the DNS with the IP address, but it did not fix the issue.

Now, I'm endeavoring to connect using MQTT Explorer on my personal computer, but I keep encountering a timeout. Could it be that I'm missing something here? I extracted this information directly from the source code.

![Sélection_017](https://github.com/hardillb/node-red-contrib-googlehome-web/assets/5030247/67208b6b-2bfb-4712-acf1-6d9fee09284b)

**Comment by hardillb** [comment]
Timeout implies a firewall is dropping packets? Are you blocking outbound connections on port 1883?

As I've said this very much looks like something on your network

**Comment by franckarts** [comment]
No, I haven't blocked any outbound connections, and it was functioning previously (with no changes made in between). I've just attempted using my phone's connection, but encountered the same issue :(.

**Comment by franckarts** [comment]
How weird, it worked once. I will investigate today.

**Comment by franckarts** [comment]
Ok, it's definitely a problem on my side. I have tried with another phone and it does work well this time.
Thanks and sorry for the noise.
