### ISSUE TITLE
HELP. Using Google node - several commands - Mancave (turn on tmancave etc)

### ISSUE THREAD

**Issue by scargill** [hardillb/node-red-contrib-googlehome-web#97]
Been using the node for ages - fine. Just moved from raspberry pi 4 to 5 - erdid all my node-red-nodes - all working - zigbee and tasmota etc. But the Google node sigts alternating betwenn connected - disconnected - couple of seconds one then couple of seconds the other continuously.

I waiterd until NR node showd said disconnected - and said "hey google - mancave off" - it worked and turned lights on. Next time didnt actually do anything even though it confirmed verbally, next time nothing, next time worked and so on - I've no idea why it's doing this, The original RPi4 is turned off.

Pi5 is working perfectly otherwise.

Ideas?

**Comment by hardillb** [comment]
Asked and answered for you twice before. You do have a second version running somewhere, I can't help you find it.

**Comment by scargill** [comment]
Hi

Sorry for this - but you may be confusing me with someone else - in the past I have asked you for help - there was an issue with DHCP I think. I can assure you I own only two Raspberry Pis - a Pi4 (2gig ram) which runs Node-Red natively using 32-bit Bookworm Pi OS - and was handling your node perfectly and has done for some time. 

The last few days we've taken a brand new Raspberry Pi 5  (4gig RAM) with the latest 64 bit Bookwork 64 bit Pi OS and this time installed Docker - so - Node-Red is running in Docker and all my nodes are working (handling Tasmota devices and Zigbee2mqtt (which also runs under Docker).  We  completed the transfer mid-afternoon and the RPi4 is turned off - there is nothing else running Node-Red of any kind.

So I remain at a loss as to why your node is stating connected then disconnected constantly,  a few seconds at a time. I have a 4A 5v supply on the RPI5 and no monitor connected - only an SSD for backup.

![image](https://github.com/hardillb/node-red-contrib-googlehome-web/assets/1889411/aead380f-1dea-4ef9-afa4-faa6f9b2b28e)

and yes I've rebooted the RPi5. Same result.

**Comment by hardillb** [comment]
Answer still stands, you have 2 MQTT client with the same client id (this might be 2, or more, config nodes, including on another machine). I really can not help you find it, it's some where on your devices.
